=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/Main.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/MainSchema"
           targetNamespace="https://example.org/ROOTMAP/MainSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="configuration" type="tns:MainConfiguration" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="MainConfiguration">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="type">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="construction" />
                        <xsd:enumeration value="initialisation" />
                        <xsd:enumeration value="visualisation" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="owner" type="xsd:string"/>
            <xsd:element name="location" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Wheat soil obstructions/rootmap.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- RootMap configuration/initialisation file                              -->
<!--                                                                        -->
<!-- FORMAT:XML                                                             -->
<!--                                                                        -->

<rootmap
        xmlns="https://example.org/ROOTMAP/MainSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/MainSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/Main.xsd">
  <!-- CONSTRUCTION CONFIGURATION -->
  <configuration>
    <name>Scoreboard Boundaries</name>
    <type>construction</type>
    <owner>ScoreboardCoordinator</owner>
    <location>Scoreboards.xml</location>
  </configuration>  
  <configuration>
    <name>Volume Objects</name>
    <type>construction</type>
    <owner>VolumeObjectCoordinator</owner>
    <location>VolumeObjects.xml</location>
  </configuration>
  <configuration>
    <name>Plant Attributes</name>
    <type>construction</type>
    <owner>SharedAttributeManager</owner>
    <location>shared_attributes/PlantAttributes.xml</location>
  </configuration>
  <configuration>
    <name>Nitrate Attributes</name>
    <type>construction</type>
    <owner>SharedAttributeManager</owner>
    <location>shared_attributes/NitrateAttributes.xml</location>
  </configuration>
  <configuration>
    <name>Phosphorus Attributes</name>
    <type>construction</type>
    <owner>SharedAttributeManager</owner>
    <location>shared_attributes/PhosphorusAttributes.xml</location>
  </configuration>
  <configuration>
    <name>Water Attributes</name>
    <type>construction</type>
    <owner>SharedAttributeManager</owner>
    <location>shared_attributes/WaterAttributes.xml</location>
  </configuration>
  <configuration>
    <name>Post Office</name>
    <type>construction</type>
    <owner>PostOffice</owner>
    <location>PostOffice.xml</location>
  </configuration>
  <configuration>
    <name>Plant Types</name>
    <type>construction</type>
    <owner>PlantCoordinator</owner>
    <location>process_data/PlantTypes.xml</location>
  </configuration>
  <configuration>
    <name>Plants</name>
    <type>construction</type>
    <owner>PlantCoordinator</owner>
    <location>process_data/Plants.xml</location>
  </configuration>
  <configuration>
    <name>Processes</name>
    <type>construction</type>
    <owner>ProcessCoordinator</owner>
    <location>process_data/Processes.xml</location>
  </configuration>

  <configuration>
    <name>Plant Initial Values</name>
    <type>initialisation</type>
    <owner>Scoreboard</owner>
    <location>shared_attributes/PlantAttributeInitialValues.xml</location>
  </configuration>
  <configuration>
    <name>Nitrate Initial Values</name>
    <type>initialisation</type>
    <owner>Scoreboard</owner>
    <location>shared_attributes/NitrateAttributeInitialValues.xml</location>
  </configuration>
  <configuration>
    <name>Phosphorus Initial Values</name>
    <type>initialisation</type>
    <owner>Scoreboard</owner>
    <location>shared_attributes/PhosphorusAttributeInitialValues.xml</location>
  </configuration>
  <configuration>
    <name>Water Initial Values</name>
    <type>initialisation</type>
    <owner>Scoreboard</owner>
    <location>shared_attributes/WaterAttributeInitialValues.xml</location>
  </configuration>

  <configuration>
    <name>Phosphorus Initial Data</name>
    <type>initialisation</type>
    <owner>Scoreboard</owner>
    <location>scoreboard_data/PhosphorusData.xml</location>
  </configuration>
  <configuration>
    <name>Nitrate Initialisation Data</name>
    <type>initialisation</type>
    <owner>Scoreboard</owner>
    <location>scoreboard_data/NitrateAmount.xml</location>
  </configuration>
  <configuration>
    <name>Bulk Density Initialisation</name>
    <type>initialisation</type>
    <owner>Scoreboard</owner>
    <location>scoreboard_data/BulkDensity.xml</location>
  </configuration>
  <configuration>
    <name>Water Initialisation Data</name>
    <type>initialisation</type>
    <owner>Scoreboard</owner>
    <location>scoreboard_data/SoilWaterContent.xml</location>
  </configuration>
  <configuration>
    <name>Water Rainfall Initialisation</name>
    <type>initialisation</type>
    <owner>Water</owner>
    <location>process_data/RainfallEvents.xml</location>
  </configuration>
  <configuration>
    <name>Output Rules</name>
    <type>initialisation</type>
    <owner>DataOutputCoordinator</owner>
    <location>OutputRules.xml</location>
  </configuration>
    <configuration>
    <name>Renderer Configuration</name>
    <type>initialisation</type>
    <owner>RenderCoordinator</owner>
    <location>Renderer.xml</location>
  </configuration>



  <!-- VISUALISATION CONFIGURATION -->
  <configuration>
    <name>Tables</name>
    <type>visualisation</type>
    <owner>TableCoordinator</owner>
    <location>Windows.xml</location>
  </configuration>
  <configuration>
    <name>Views</name>
    <type>visualisation</type>
    <owner>ViewCoordinator</owner>
    <location>Windows.xml</location>
  </configuration>
  <configuration>
    <name>View3D</name>
    <type>visualisation</type>
    <owner>View3DCoordinator</owner>
    <location>Windows.xml</location>
  </configuration>
</rootmap>
