=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/OutputRules.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/OutputRulesSchema"
           targetNamespace="https://example.org/ROOTMAP/OutputRulesSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="initialisation" type="tns:Initialisation" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Initialisation">
        <xsd:sequence>
            <xsd:element name="owner" type="xsd:string" minOccurs="1" maxOccurs="1" />
            <xsd:element name="outputrule" type="tns:OutputRule" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="OutputRule">
        <xsd:all>
            <xsd:element name="source" type="xsd:string" minOccurs="1" />
            <xsd:element name="type" type="xsd:string"  minOccurs="1" />
            <xsd:element name="stratum" type="xsd:string" minOccurs="1" />
            <xsd:element name="characteristic" type="xsd:string" minOccurs="0" >
                <xsd:annotation>
                    <xsd:documentation>Characteristic is meaningful for the type/source combination.
                    If this OutputRule's type is ScoreboardData, Characteristic refers to a specific Scoreboard Characteristic.
                    Otherwise, it is optional and may be used as a more general descriptor.</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="filename" type="xsd:string" minOccurs="1">
                <xsd:annotation>
                    <xsd:documentation>Filename accepts % formatting codes for strftime.
                    It pre-processes URL % formatted values before passing to strftime, eg. when using %20 for trailing spaces.
                    It pre-processes extra format specifiers:
                        %C counter for number of outputs for this object so far (UNSUPPORTED)
                        %R raw timestamp in seconds from T=0 (UNSUPPORTED)
                        both of these accept the usual %d format specifiers, eg. "%.3C" produces a 3-digit leading-zero-padded.
                    The following example produces a filename like RootLength_YYYYmmdd-HHMMSS.txt
                    Don't confuse the lowercase and uppercase 'm'.
           m=month, M=Minute</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="specification1" type="xsd:string" minOccurs="0" >
                <xsd:annotation>
                    <xsd:documentation>Specification1 is meaningful to the type.
                    For "ScoreboardData", specification1 is the dimension order.</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="specification2" type="xsd:string" minOccurs="0" >
                <xsd:annotation>
                    <xsd:documentation>Specification2 is meaningful to the type.
                    For "RaytracerData", specification2 sets the method of ScoreboardBox rendering.
                    DF3: uses POV-Ray's voxel-based density field format to represent the whole Scoreboard. Typically better for geometrically regular Scoreboard boundaries.
                    SB: uses a rectangular prism of translucent media to represent each ScoreboardBox. Typically better for irregular Scoreboard box sizes.</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="reopen" minOccurs="1" >
                <xsd:simpleType>
                    <xsd:annotation>
                        <xsd:documentation>Output file reopening strategy. Row-structured output rules which write self-contained lines to a file (e.g. CSV) may use "append". All RaytracerData output rules must use "overwrite" as their file format does not support appending.</xsd:documentation>
                    </xsd:annotation>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="append" />
                        <xsd:enumeration value="overwrite" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="when" type="tns:When" minOccurs="1" />
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="When">
        <xsd:sequence>
            <xsd:element name="count" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:annotation>
                        <xsd:documentation>count = 0: repeat output continuously using the specified interval or frequency until the simulation completes. If no interval or frequency, no output will be produced.
                    count > 0: if no interval or frequency, interval will be computed as (total simulation runtime)/count. Otherwise output will occur (count) times from initialtime at the specified interval or with the specified frequency, unless simulation completes earlier.</xsd:documentation>
                    </xsd:annotation>
                    <xsd:restriction base="xsd:int">
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="initialtime" type="tns:YmdHMS" minOccurs="0" maxOccurs="1" />
            <xsd:choice>
                <xsd:element name="frequency" type="tns:YmdHMS" minOccurs="0" maxOccurs="1" />
                <xsd:element name="interval" type="tns:YmdHMS" minOccurs="0" maxOccurs="1" />
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/config_Genotype85/OutputRules.xml
<?xml version="1.0" encoding="utf-8"?>

<rootmap
        xmlns="https://example.org/ROOTMAP/OutputRulesSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/OutputRulesSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/OutputRules.xsd">


  <initialisation>
    <owner>DataOutputCoordinator</owner>
    <outputrule>
      <type>ScoreboardData</type>
      <source>PlantCoordinator</source>
      <!-- characteristic is meaningful for the type/source combination
           It applies in the general non-scoreboard sense of the term
           also, you see -->
      <characteristic>Root Length Wrap None Plant 85</characteristic>
      <stratum>Soil</stratum>
      <!-- accepts % formatting codes for strftime -->
      <!-- Pre-processes URL % formatted values before passing to strftime
           eg. use %20 for trailing spaces -->
      <!-- Pre-processes extra format specifiers:
           %C counter for number of outputs for this object so far (UNSUPPORTED)
           %R raw timestamp in seconds from T=0 (UNSUPPORTED)
           both of these accept the usual %d format specifiers,
           eg. "%.3C" produces a 3-digit leading-zero-padded.
           The following example produces a filename like
           RootLength_YYYYmmdd-HHMMSS.txt
           PLEASE ensure you don't confuse the lowercase and uppercase 'm'.
           m=month, M=Minute -->
      <filename>TotalRootLengthPlant85.txt</filename>
      <!-- specification1 and specification2 are meaningful to the type.
           For "ScoreboardData", specification1 is the dimension order. -->
      <specification1>X,Z,Y</specification1>
      <!-- how to handle current contents when openning a non-empty file:
           append|overwrite (default=overwrite) -->
      <reopen>overwrite</reopen>
      <when>
        <!-- a count of zero is to repeat ad infinitum -->
        <count>0</count>
        <!-- For exporting "every" so often, use the initialtime and frequency tags
             Year,Month,Day,Hour,Minute,Second -->
        <interval>0,0,34,0,0,0</interval>
        <initialtime>0,0,0,0,0,0</initialtime>
      </when>
    </outputrule>
  </initialisation>

</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Wheat with compaction/RaytraceOnlyOutputRules.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- If specifying a directory for output, ensure it exists before running ROOTMAP -->

<rootmap
        xmlns="https://example.org/ROOTMAP/OutputRulesSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/OutputRulesSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/OutputRules.xsd">
<initialisation>
    <owner>DataOutputCoordinator</owner>
    <outputrule>
        <!-- For "RaytracerData", the <source> tag controls both
            (A) What will be the primary source for raytraced visualisation, and
            (B) Where the the raytraced scene will be centred.  
            
              If the <source> is a Plant name, its roots will be drawn and halfway down the Scoreboard from its <origin> point will be the centre. (see Plants.xml)
              If the <source> is the PlantCoordinator, all Plants' roots will be drawn and halfway down the Scoreboard from the geometric centre of all Plants' origins will be the centre.
              If the <source> is the ScoreboardRenderer, all Scoreboard boxes will be drawn and the geometric centre of the Scoreboards will be the centre. -->
        <source>ScoreboardRenderer</source>
        <type>RaytracerData</type>
        <stratum>Soil</stratum>
        <!--    Filename should be left as the default: Raytracer/DF3_Rootmap_Data%04u.inc (or Raytracer/SB_Rootmap_Data%04u.inc).
            The %04u suffix indicates that each frame's filename will be serialised
            with a 4-digit [U]nsigned integer (i.e. 0000, 0001, 0002, 0003, etc).
            The first file generated contains a list of all (zero or more) subsequent filenames.
            It is referenced by the main Rootmap_Scene.pov file
            to load every frame into the POV-ray scene. 
            (One serialised include file is generated for each frame)
            Count starts at zero due to convention.
            
            If changed, the new filename must be substituted for DF3_Rootmap_Data0000.inc
            in Rootmap_Scene.pov. The unserialised filename prefix must not end with a digit
            (i.e. Rootmap1%04u.inc is illegal). File extension must be .inc.
            -->
        <filename>Raytracer/DF3_Rootmap_Data%04u.inc</filename>
        <!-- specification1 is meaningful to the type.
            For "RaytracerData", specification1 is a comma-delimited list of extra Process names to be raytraced.
            
            (1) Type "all" to raytrace output from everything: the <source>, plus all raytracer-capable Processes,
                plus visualisation of all Scoreboard boxes (see Windows.xml : ViewCoordinator and View3DCoordinator).
            (2) Type a comma-delimited list of one or more Processes and/or "ScoreboardRenderer" to raytrace output from these
                in addition to the <source>.  E.g. <specification1>Nitrate, ScoreboardRenderer</specification1>
            (3) Leave <specification1> blank (or absent entirely) to raytrace output from the <source> only.     -->
        <specification1>PlantCoordinator,Nitrate</specification1>
        <!-- specification2 is used for setting the method of ScoreboardBox rendering.
			 <specification2>DF3</specification2> uses POV-ray's voxel-based density field format to represent the whole Scoreboard,
			 <specification2>SB</specification2> uses a rectangular prism of translucent media to represent each ScoreboardBox.
			 As a rule of thumb, DF3 is better for mathematically regular Scoreboard boundaries,
			 and SB is better for irregular Scoreboard box sizes.			 -->
        <specification2>DF3</specification2>
        <!-- <reopen> should always be set to OVERWRITE. POV-ray relies on the files generated by Rootmap
            being formatted correctly; appending data to existing files would corrupt them. -->
        <reopen>overwrite</reopen>
        <when>
            <!-- a count of zero is to repeat ad infinitum -->
            <count>5</count>
            <!-- Leave out all <when> elements except for count,
                (or set <interval> to all zeros) to use <count> as the frame count
                throughout the whole simulation. That is, <interval> will be calculated
                as [total sim runtime] / <count>.
                Of course if <count> is zero in this case, no output will be produced. -->
            <!--interval>0,0,2,12,0,0</interval>
            <initialtime>0,0,0,18,0,0</initialtime-->
        </when>
    </outputrule>
	<outputrule>
	  <source>ViewCoordinator</source>
	  <type>ViewCapture</type>
	  <stratum>Soil</stratum>
	  <filename>2D_test %02i.png</filename>
	  <!-- For ViewCaptureOutputStrategy, <specification1> is the zero-based index of the desired View window --> 
	  <specification1>0</specification1>
	  <!-- Use only <reopen>overwrite</reopen> -->
	  <reopen>overwrite</reopen>
	  <when>
		<!-- a count of zero is to repeat ad infinitum -->
		<count>10</count>
		<!-- For exporting "every" so often, use the initialtime and frequency tags
			 Year,Month,Day,Hour,Minute,Second -->
		<interval>0,0,0,6,0,0</interval>
		<initialtime>0,0,0,0,10,0</initialtime>
	  </when>
	</outputrule>
	<outputrule>
	  <source>View3DCoordinator</source>
	  <type>ViewCapture</type>
	  <stratum>Soil</stratum>
	  <filename>3D_test %02i.png</filename>
	  <!-- For ViewCaptureOutputStrategy, <specification1> is the zero-based index of the desired View window --> 
	  <specification1>0</specification1>
	  <!-- Use only <reopen>overwrite</reopen> -->
	  <reopen>overwrite</reopen>
	  <when>
		<!-- a count of zero is to repeat ad infinitum -->
		<count>50</count>
		<!-- For exporting "every" so often, use the initialtime and frequency tags
			 Year,Month,Day,Hour,Minute,Second -->
		<interval>0,0,0,6,0,0</interval>
		<initialtime>0,0,0,0,10,0</initialtime>
	  </when>
	</outputrule>
	</initialisation>
	
</rootmap>
