=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/PlantTypes.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/PlantTypesSchema"
           targetNamespace="https://example.org/ROOTMAP/PlantTypesSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="construction" type="tns:PlantTypes" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="PlantTypes">
        <xsd:sequence>
            <xsd:element name="owner" type="xsd:string" fixed="PlantCoordinator" />
            <xsd:element name="planttype" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="name" type="xsd:string" />
                        <xsd:element name="roots_to_foliage_ratio" type="tns:PositiveDecimal" />
                        <xsd:element name="vegetate_to_reproduce_ratio" type="tns:PositiveDecimal" />
                        <xsd:element name="structure_to_photosynthesize_ratio" type="tns:PositiveDecimal" />
                        <xsd:element name="initial_seminal_deflection" type="xsd:decimal" />
                        <xsd:element name="germination_lag" type="tns:PositiveDecimal" />
                        <xsd:element name="first_seminal_probability" type="tns:UnitInterval" />
                        <xsd:element name="temperature_of_zero_growth" type="tns:Temperature" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Genotype 84 Soil config/process_data/PlantTypes.xml
<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>

<!-- Plant Types file                                                       -->
<!--                                                                        -->
<!-- FORMAT:XML                                                             -->
<!--                                                                        -->
<!-- NO C-style comments                                                    -->
<!--                                                                        -->
<rootmap
        xmlns="https://example.org/ROOTMAP/PlantTypesSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/PlantTypesSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/PlantTypes.xsd">
  <construction>
    <owner>PlantCoordinator</owner>
    <planttype>
      <name>RootMap Plant Type</name>
      <roots_to_foliage_ratio>1.0</roots_to_foliage_ratio>
      <vegetate_to_reproduce_ratio>1.0</vegetate_to_reproduce_ratio>
      <structure_to_photosynthesize_ratio>1.0</structure_to_photosynthesize_ratio>
      <initial_seminal_deflection>1.0</initial_seminal_deflection>
      <germination_lag>1.0</germination_lag>
      <first_seminal_probability>1.0</first_seminal_probability>
      <temperature_of_zero_growth>7.0</temperature_of_zero_growth>
    </planttype>
  </construction>
</rootmap>
