=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/Plants.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/PlantsSchema"
           targetNamespace="https://example.org/ROOTMAP/PlantsSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="construction" type="tns:Plants" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Plants">
        <xsd:sequence>
            <xsd:element name="owner" type="xsd:string" fixed="PlantCoordinator" />
            <xsd:element name="plant" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="name" type="xsd:string" />
                        <xsd:element name="type" type="xsd:string" />
                        <xsd:element name="origin" type="tns:Coordinate3D" />
                        <xsd:element name="seed_location" type="tns:Coordinate3D" />
                        <xsd:element name="seeding_time" type="tns:PositiveDecimal">
                            <xsd:annotation>
                                <xsd:documentation>Seeding time is in days from time zero.
                                </xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                        <!-- Are seminal and/or nodal axes required? -->
                        <xsd:element name="seminal_axis" type="tns:Axis" minOccurs="0" maxOccurs="unbounded" />
                        <xsd:element name="nodal_axis" type="tns:Axis" minOccurs="0" maxOccurs="unbounded" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Axis">
        <xsd:annotation>
            <xsd:documentation>Describes a seminal or nodal axis of a plant.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="start_lag" type="xsd:decimal" maxOccurs="1" />
            <xsd:element name="probability" type="tns:UnitInterval" maxOccurs="1" />
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Genotype 44 Soil config/process_data/Plants.xml
<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>

<!-- Plants file                                                            -->
<!--                                                                        -->
<!-- FORMAT:XML                                                             -->
<!--                                                                        -->
<!-- NO C-style comments                                                    -->
<!--                                                                        -->
<rootmap
        xmlns="https://example.org/ROOTMAP/PlantsSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/PlantsSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/Plants.xsd">
  <construction>
    <owner>PlantCoordinator</owner>
    <plant>
      <name>Plant 44</name>
      <type>RootMap Plant Type</type>
      <!-- origin and seed_location are X,Y,Z no spaces -->
      <origin>5.0,5.0,0.0</origin>
      <seed_location>5.0,5.0,0.5</seed_location>
      <!-- seeding time is in days from time zero -->
      <seeding_time>1.0</seeding_time>
      <seminal_axis>
        <start_lag>1.0</start_lag>
        <probability>1.0</probability>
      </seminal_axis>
      <seminal_axis>
        <start_lag>1.0</start_lag>
        <probability>0.0</probability>
      </seminal_axis>
      <nodal_axis>
        <start_lag>100.0</start_lag>
        <probability>0.0</probability>
      </nodal_axis>
    </plant>
  </construction>
</rootmap>
