=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/PostOffice.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/PostOfficeSchema"
           targetNamespace="https://example.org/ROOTMAP/PostOfficeSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="construction" type="tns:PostOfficeConstruction" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="PostOfficeConstruction">
        <xsd:sequence>
            <xsd:element name="owner" type="xsd:string"/>
            <xsd:element name="postoffice">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="random_seed" type="xsd:unsignedInt" minOccurs="0" maxOccurs="1" />
                        <xsd:element name="previous" type="tns:DateTime" maxOccurs="1" />
                        <xsd:element name="now" type="tns:DateTime" maxOccurs="1" />
                        <xsd:element name="next_start" type="tns:DateTime" maxOccurs="1" />
                        <xsd:element name="next_end" type="tns:DateTime" maxOccurs="1" />
                        <xsd:element name="defaultruntime" type="tns:YmdHMS" maxOccurs="1" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/config_Genotype85/PostOffice.xml
<?xml version="1.0" encoding="utf-8"?>

<rootmap
        xmlns="https://example.org/ROOTMAP/PostOfficeSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/PostOfficeSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/PostOffice.xsd">
  <construction>
    <owner>PostOffice</owner>
    <postoffice>
      <!-- Year,Month,Day,Hour,Minute,Second -->
      <previous>1990,1,1,9,0,0</previous>
      <now>1990,1,1,9,0,0</now>
      <next_start>1990,1,1,9,0,0</next_start>
      <next_end>1990,1,5,0,0,0</next_end>

      <!-- Years,Months,Days,Hours,Minutes,Seconds -->
      <defaultruntime>0,0,35,0,0,0</defaultruntime>
    </postoffice>
    
  </construction>
</rootmap>
