=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/Processes.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/ProcessesSchema"
           targetNamespace="https://example.org/ROOTMAP/ProcessesSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="construction" type="tns:Processes" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Processes">
        <xsd:sequence>
            <xsd:element name="owner" type="xsd:string" fixed="ProcessCoordinator" />
            <xsd:element name="process" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="name" type="xsd:string" />
                        <xsd:element name="override" type="xsd:boolean" />
                        <xsd:element name="scoreboard" type="xsd:string" />
                        <!-- TODO restrict to Grow, Misc etc. -->
                        <xsd:element name="activitytype" type="xsd:string" />
                        <xsd:element name="characteristic" type="tns:Characteristic" minOccurs="0" maxOccurs="unbounded" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Characteristic">
        <xsd:sequence>
            <xsd:element name="minimum" type="xsd:double">
                <xsd:annotation>
                    <xsd:documentation>Supports scientific notation and the special values INF (infinity), -INF (negative infinity) an NaN (not a number).
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="maximum" type="xsd:double">
                <xsd:annotation>
                    <xsd:documentation>Supports scientific notation and the special values INF (infinity), -INF (negative infinity) an NaN (not a number).
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="default" type="xsd:double">
                <xsd:annotation>
                    <xsd:documentation>Supports scientific notation and the special values INF (infinity), -INF (negative infinity) an NaN (not a number).
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="units" type="xsd:string" />
            <xsd:element name="visible" type="xsd:boolean" />
            <xsd:element name="editable" type="xsd:boolean" />
            <xsd:element name="tobesaved" type="xsd:boolean" />
            <xsd:element name="specialperboxinfo" type="xsd:boolean" />
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Wheat with compaction/process_data/Processes.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<!-- Simulating luping root growth in a sandy soil                          -->
<!-- Plants file                                                            -->
<!--                                                                        -->
<!-- FORMAT:XML                                                             -->
<!--                                                                        -->
<!-- NO C-style comments                                                    -->
<!--                                                                        -->
<rootmap
        xmlns="https://example.org/ROOTMAP/ProcessesSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ProcessesSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/Processes.xsd">
  <construction>

    <owner>ProcessCoordinator</owner>
    <process>
      <name>PlantCoordinator</name>
      <override>true</override>
      <scoreboard>All</scoreboard>
      <activitytype>Grow</activitytype>
    </process>

    <process>
      <name>VolumeObjectCoordinator</name>
      <override>true</override>
      <scoreboard>Soil</scoreboard>
      <activitytype>Misc</activitytype>
    </process>

	<process>
      <name>ScoreboardRenderer</name>
      <override>true</override>
      <scoreboard>All</scoreboard>
      <activitytype>Misc</activitytype>
    </process>

    <process>
      <name>Ammonium</name>
      <override>false</override>
      <scoreboard>Soil</scoreboard>
      <activitytype>Misc</activitytype>
      <characteristic>
        <minimum>0.0</minimum>
        <maximum>30.0</maximum>
        <default>0.0</default>
        <name>Ammonium</name>
        <units>&#x3BC;g/ml</units>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
      </characteristic>
      <characteristic>
        <minimum>0.0</minimum>
        <maximum>1000.0</maximum>
        <default>0.0</default>
        <name>Ammonium Received Buffer</name>
        <units>&#x3BC;g/ml</units>
        <visible>false</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
      </characteristic>
    </process>


    <process>
      <name>Extractable Aluminium</name>
      <override>false</override>
      <scoreboard>Soil</scoreboard>
      <activitytype>NONE</activitytype>
      <characteristic>
        <minimum>0.0</minimum>
        <maximum>250.0</maximum>
        <default>0.0</default>
        <name>Extractable Aluminium</name>
        <units>&#x3BC;M (CaCl)</units>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
      </characteristic>
    </process>


    <process>
      <name>Nitrate</name>
      <override>true</override>
      <scoreboard>Soil</scoreboard>
      <activitytype>Leac</activitytype>
      <characteristic>
        <minimum>0</minimum>
        <maximum>40</maximum>
        <default>1.4</default>
        <name>Nitrate Concentration</name>
        <units>&#x3BC;ugN/cm^3(water)</units>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
      </characteristic>
      <characteristic>
        <minimum>0</minimum>
        <maximum>1e6</maximum>
        <default>0</default>
        <name>Nitrate Leached</name>
        <units>ugN/cm^2</units>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
      </characteristic>
      <characteristic>
        <minimum>0</minimum>
        <maximum>infinity</maximum>
        <default>0</default>
        <name>Internal Workings</name>
        <units>none</units>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
      </characteristic>
      <characteristic>
        <minimum>0</minimum>
        <maximum>1000</maximum>
        <default>90</default>
        <name>Nitrate Amount</name>
        <!-- Nitrate Amount &#x3BC;ugN during the simulation, initially input as ugN/g -->
        <units>&#x3BC;ug N</units>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
      </characteristic>
      <characteristic>
        <minimum>0.0</minimum>
        <maximum>1000.0</maximum>
        <default>3.0</default>
        <name>Nitrate Renew</name>
        <units>µg/g</units>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
      </characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>1000</maximum>
			<default>0</default>
			<name>Nitrate Amount Check</name>
			<units>&#x3BC;g N</units>
			<visible>false</visible>
			<editable>false</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>1</maximum>
			<default>0</default>
			<name>Fraction of Fertiliser N</name>
			<units>NONE</units>
			<visible>true</visible>
			<editable>false</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>1</maximum>
			<default>1.58</default>
			<name>Coefficient c</name>
			<units>NONE</units>
			<visible>true</visible>
			<editable>false</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>-1000</minimum>
			<maximum>1</maximum>
			<default>-0.01</default>
			<name>Coefficient d</name>
			<units>NONE</units>
			<visible>true</visible>
			<editable>false</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>100</maximum>
			<default>3.0</default>
			<name>Dispersivity</name>
			<units>cm</units>
			<visible>true</visible>
			<editable>false</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>10000</maximum>
			<default>0.0</default>
			<name>Fertiliser N</name>
			<units>ugN</units>
			<visible>true</visible>
			<editable>true</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>10000</maximum>
			<default>0.0</default>
			<name>Background N</name>
			<units>ugN</units>
			<visible>true</visible>
			<editable>false</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>10000</maximum>
			<default>0.0</default>
			<name>Added N</name>
			<units>ugN</units>
			<visible>true</visible>
			<editable>false</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>10000</maximum>
			<default>0.0</default>
			<name>Added N2</name>
			<units>ugN</units>
			<visible>true</visible>
			<editable>false</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>10</maximum>
			<default>1.09e-7</default>
			<name>Rate Constant</name>
			<units>s-1</units>
			<visible>true</visible>
			<editable>true</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>100</maximum>
			<default>40</default>
			<name>Rate Constant Temperature</name>
			<units>C</units>
			<visible>true</visible>
			<editable>true</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>5</maximum>
			<default>1.8</default>
			<name>Q10</name>
			<units>None</units>
			<visible>true</visible>
			<editable>true</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>1000</maximum>
			<default>20.0</default>
			<name>Mineralisable N</name>
			<units>µg/g</units>
			<visible>true</visible>
			<editable>true</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>1000</maximum>
			<default>0.0</default>
			<name>Mineralised N</name>
			<units>µgN</units>
			<visible>true</visible>
			<editable>true</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>1</maximum>
			<default>1.0</default>
			<name>Estimate Initial Soil Temp Profile</name>
			<units>None</units>
			<visible>true</visible>
			<editable>true</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
		<characteristic>
			<minimum>0</minimum>
			<maximum>1</maximum>
			<default>0.2</default>
			<name>Thermal Diffusivity</name>
			<units>cm2s-1</units>
			<visible>true</visible>
			<editable>true</editable>
			<tobesaved>true</tobesaved>
			<specialperboxinfo>false</specialperboxinfo>
		</characteristic>
      <characteristic>
        <minimum>0</minimum>
