=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/Renderer.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/ViewSchema"
           targetNamespace="https://example.org/ROOTMAP/ViewSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="initialisation" type="tns:Renderer" minOccurs="0" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Renderer">
        <xsd:sequence>
            <xsd:element name="owner" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="characteristic_colour_info" type="tns:CharacteristicColourInfo" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="CharacteristicColourInfo">
        <xsd:sequence>
            <xsd:element name="colour_min" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:int">
                        <xsd:minInclusive value="0"/>
                        <xsd:maxInclusive value="255"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="colour_max" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:int">
                        <xsd:minInclusive value="0"/>
                        <xsd:maxInclusive value="255"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="characteristic_min" type="xsd:decimal" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="characteristic_max" type="xsd:decimal" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="process_name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="characteristic_name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Genotype 120 Soil config/Renderer.xml
<?xml version="1.0" encoding="utf-8"?>

<rootmap
        xmlns="https://example.org/ROOTMAP/ViewSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ViewSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/Renderer.xsd">
	<initialisation>
		<owner>RenderCoordinator</owner>
		<characteristic_colour_info>
		  <colour_min>0</colour_min>
		  <colour_max>255</colour_max>
		  <characteristic_min>0.0</characteristic_min>
		  <characteristic_max>1000.0</characteristic_max>
		  <process_name>Phosphorus</process_name>
            <characteristic_name>Total Labile P VolumeObject 1</characteristic_name>
		</characteristic_colour_info>
		<characteristic_colour_info>
		  <colour_min>0</colour_min>
		  <colour_max>255</colour_max>
		  <characteristic_min>0.0</characteristic_min>
		  <characteristic_max>1000.0</characteristic_max>
		  <process_name>Nitrate</process_name>
            <characteristic_name>Nitrate Concentration VolumeObject 1</characteristic_name>
		</characteristic_colour_info>
		<characteristic_colour_info>
		  <colour_min>0</colour_min>
		  <colour_max>255</colour_max>
		  <characteristic_min>0.0</characteristic_min>
		  <characteristic_max>100.0</characteristic_max>
		  <process_name>Water</process_name>
            <characteristic_name>Water Content VolumeObject 1</characteristic_name>
		</characteristic_colour_info>
		<characteristic_colour_info>
		  <colour_min>0</colour_min>
		  <colour_max>255</colour_max>
		  <characteristic_min>5.0</characteristic_min>
		  <characteristic_max>180.0</characteristic_max>
		  <process_name>Nitrate</process_name>
            <characteristic_name>Nitrate Amount VolumeObject 1</characteristic_name>
		</characteristic_colour_info>
		<characteristic_colour_info>
		  <colour_min>0</colour_min>
		  <colour_max>255</colour_max>
		  <characteristic_min>5.0</characteristic_min>
		  <characteristic_max>17.0</characteristic_max>
		  <process_name>Extractable Aluminium</process_name>
		  <characteristic_name>Extractable Aluminium</characteristic_name>
		</characteristic_colour_info>
	</initialisation>
</rootmap>
