=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/ScoreboardData.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/ScoreboardDataSchema"
           targetNamespace="https://example.org/ROOTMAP/ScoreboardDataSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="initialisation" type="tns:ScoreboardData" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="ScoreboardData">
        <xsd:sequence>
            <xsd:element name="owner" type="xsd:string" fixed="Scoreboard" />
            <xsd:element name="scoreboarddata" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="process" type="xsd:string" />
                        <xsd:element name="characteristic" type="xsd:string" />
                        <!-- TODO restrict to valid scheme definitions? -->
                        <xsd:element name="scheme" type="xsd:string" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/config_Genotype85/shared_attributes/PlantAttributeInitialValues.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<rootmap
        xmlns="https://example.org/ROOTMAP/ScoreboardDataSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ScoreboardDataSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/ScoreboardData.xsd">
  <initialisation>
    <owner>Scoreboard</owner>
    <!-- Plant SharedAttributes -->
    <!-- Growth Rate per-Plant per-RootOrder -->
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Root P Plasticity Factor Plant 1 RootOrder0 VolumeObject [none]</characteristic>
      <scheme>set scoreboard value=1.0;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Root P Plasticity Factor Plant 1 RootOrder1 VolumeObject [none]</characteristic>
      <scheme>set scoreboard value=1.0;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Root P Plasticity Factor Plant 1 RootOrder2 VolumeObject [none]</characteristic>
      <scheme>set scoreboard value=1.0;</scheme>
    </scoreboarddata>
  </initialisation>
</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/config_Genotype85/scoreboard_data/NitrateAmount.xml
<?xml version="1.0" encoding="utf-8"?>
<rootmap
        xmlns="https://example.org/ROOTMAP/ScoreboardDataSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ScoreboardDataSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/ScoreboardData.xsd">
  <initialisation>
    <owner>Scoreboard</owner>
    <scoreboarddata>
      <!-- Nitrate Amount &#x3BC;ugN during the simulation, initially input as ugN/g, same for both the Yellow Sand and Vertosol Soil simulations-->
      <process>Nitrate</process>
      <characteristic>Nitrate Amount VolumeObject [none]</characteristic>
      <scheme>
        set scoreboard value=4.7;
      </scheme>
    </scoreboarddata>
    <scoreboarddata>
      <!-- Nitrate Amount &#x3BC;ugN during the simulation, initially input as ugN/g, same for both the Yellow Sand and Vertosol Soil simulations-->
      <process>Nitrate</process>
      <characteristic>Nitrate Amount VolumeObject 1</characteristic>
      <scheme>
        set scoreboard value=4.7;
      </scheme>
    </scoreboarddata>
  </initialisation>
</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Wheat with compaction/scoreboard_data/SoilWaterContent.xml
<?xml version="1.0" encoding="utf-8"?>
<rootmap
        xmlns="https://example.org/ROOTMAP/ScoreboardDataSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ScoreboardDataSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/ScoreboardData.xsd">
<initialisation>

    <!-- Soil W for modelling lupin root growth in pots, simulations in sandy soil -->

    <owner>Scoreboard</owner>

    <scoreboarddata>

      <!-- water

        Initial soil water content -->

      <process>Water</process>

      <characteristic>Water Content VolumeObject [none]</characteristic>

      <scheme>

        set scoreboard value=0.15;

      </scheme>

    </scoreboarddata>

    <scoreboarddata>

      <!-- water

        Initial soil water content -->

      <process>Water</process>

      <characteristic>Water Content VolumeObject 1</characteristic>

      <scheme>

        set scoreboard value=0.15;

      </scheme>

    </scoreboarddata>

  </initialisation>


</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/default/shared_attributes/WaterAttributeInitialValues.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rootmap
        xmlns="https://example.org/ROOTMAP/ScoreboardDataSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ScoreboardDataSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/ScoreboardData.xsd">
    <initialisation>
        <owner>Scoreboard</owner>
        <scoreboarddata>
            <!-- Water SharedAttributes -->
            <process>Water</process>
            <characteristic>Water Flux Plant 1 RootOrder0 VolumeObject [none]</characteristic>
            <scheme>set scoreboard value=0.00;</scheme>
        </scoreboarddata>
        <scoreboarddata>
            <process>Water</process>
            <characteristic>Water Flux Plant 1 RootOrder1 VolumeObject [none]</characteristic>
            <scheme>set scoreboard value=0.00;</scheme>
        </scoreboarddata>
        <scoreboarddata>
            <process>Water</process>
            <characteristic>Water Flux Plant 1 RootOrder2 VolumeObject [none]</characteristic>
            <scheme>set scoreboard value=0.00;</scheme>
        </scoreboarddata>

        <scoreboarddata>
            <!-- Water SharedAttributes -->
            <process>Water</process>
            <characteristic>Water Flux Plant 1 RootOrder0 VolumeObject 1</characteristic>
            <scheme>set scoreboard value=0.00;</scheme>
        </scoreboarddata>
        <scoreboarddata>
            <process>Water</process>
            <characteristic>Water Flux Plant 1 RootOrder1 VolumeObject 1</characteristic>
            <scheme>set scoreboard value=0.00;</scheme>
        </scoreboarddata>
        <scoreboarddata>
            <process>Water</process>
            <characteristic>Water Flux Plant 1 RootOrder2 VolumeObject 1</characteristic>
            <scheme>set scoreboard value=0.00;</scheme>
        </scoreboarddata>
        <scoreboarddata>
            <!-- Water SharedAttributes -->
            <process>Water</process>
            <characteristic>Water Flux Plant 2 RootOrder0 VolumeObject 1</characteristic>
            <scheme>set scoreboard value=0.00;</scheme>
        </scoreboarddata>
        <scoreboarddata>
            <process>Water</process>
            <characteristic>Water Flux Plant 2 RootOrder1 VolumeObject 1</characteristic>
            <scheme>set scoreboard value=0.00;</scheme>
        </scoreboarddata>
        <scoreboarddata>
            <process>Water</process>
            <characteristic>Water Flux Plant 2 RootOrder2 VolumeObject 1</characteristic>
            <scheme>set scoreboard value=0.00;</scheme>
        </scoreboarddata>
        <scoreboarddata>
            <!-- Water SharedAttributes -->
            <process>Water</process>
            <characteristic>Water Flux Plant 3 RootOrder0 VolumeObject 1</characteristic>
            <scheme>set scoreboard value=0.00;</scheme>
        </scoreboarddata>
        <scoreboarddata>
            <process>Water</process>
            <characteristic>Water Flux Plant 3 RootOrder1 VolumeObject 1</characteristic>
            <scheme>set scoreboard value=0.00;</scheme>
        </scoreboarddata>
        <scoreboarddata>
            <process>Water</process>
            <characteristic>Water Flux Plant 3 RootOrder2 VolumeObject 1</characteristic>
            <scheme>set scoreboard value=0.00;</scheme>
        </scoreboarddata>
    </initialisation>
</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Wheat soil obstructions/scoreboard_data/PhosphorusData.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Soil P for modelling lupin root growth in pots, simulations in sandy soil -->
<rootmap
        xmlns="https://example.org/ROOTMAP/ScoreboardDataSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ScoreboardDataSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/ScoreboardData.xsd">
  <initialisation>

    <owner>Scoreboard</owner>

    <scoreboarddata>

      <process>Phosphorus</process>

      <!-- Total Labile P µgP/g in each soil cube, or µgP/mL for nutrient solution simulations-->

      <characteristic>Total Labile P VolumeObject [none]</characteristic>

      <scheme>

        set scoreboard value=50.0;

      </scheme>

    </scoreboarddata>

    <scoreboarddata>

      <process>Phosphorus</process>

      <!-- Total Labile P µgP/g in each soil cube, or µgP/mL for nutrient solution simulations-->

      <characteristic>Total Labile P VolumeObject 1</characteristic>

      <scheme>

        set scoreboard value=50.0;

      </scheme>

    </scoreboarddata>
	    
	<scoreboarddata>

      <process>Phosphorus</process>

      <!-- Total Labile P µgP/g in each soil cube, or µgP/mL for nutrient solution simulations-->

      <characteristic>Total Labile P VolumeObject 2</characteristic>

      <scheme>

        set scoreboard value=9.0;

      </scheme>

    </scoreboarddata>

  </initialisation>
  </rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Genotype 71 Soil config/shared_attributes/PlantAttributeInitialValues.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<rootmap
        xmlns="https://example.org/ROOTMAP/ScoreboardDataSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ScoreboardDataSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/ScoreboardData.xsd">
  <initialisation>
    <owner>Scoreboard</owner>
    <!-- Plant SharedAttributes -->
    <!-- Growth Rate per-Plant per-RootOrder -->
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Growth Rate Max Plant 71 RootOrder0</characteristic>
      <scheme>set scoreboard value=0.22;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Growth Rate Max Plant 71 RootOrder1</characteristic>
      <scheme>set scoreboard value=0.03;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Growth Rate Max Plant 71 RootOrder2</characteristic>
      <scheme>set scoreboard value=0.04;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Growth Rate Max Plant 71 RootOrder>=3</characteristic>
      <scheme>set scoreboard value=0.04;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Root P Plasticity Factor Plant 71 RootOrder0</characteristic>
      <scheme>set scoreboard value=1.0;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Root P Plasticity Factor Plant 71 RootOrder1</characteristic>
      <scheme>set scoreboard value=1.0;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Root P Plasticity Factor Plant 71 RootOrder2</characteristic>
      <scheme>set scoreboard value=1.0;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Growth Rate Plant 71 RootOrder0</characteristic>
      <scheme>set scoreboard value=0.08;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Growth Rate Plant 71 RootOrder1</characteristic>
      <scheme>set scoreboard value=0.04;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Growth Rate Plant 71 RootOrder2</characteristic>
      <scheme>set scoreboard value=0.02;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Growth Rate Plant 71 RootOrder>=3</characteristic>
      <scheme>set scoreboard value=0.01;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Final Branch Interval Plant 71 RootOrder0</characteristic>
      <scheme>
        set scoreboard value=0.62;
        set plane Z=1 value=0.27;
        set plane Z=2 value=0.27;
        set plane Z=3 value=0.27;
        set plane Z=4 value=0.27;
        set plane Z=5 value=0.27;
        set plane Z=6 value=0.27;
        set plane Z=7 value=0.29;
        set plane Z=8 value=0.29;
        set plane Z=9 value=0.29;
        set plane Z=10 value=0.29;
        set plane Z=11 value=0.45;
        set plane Z=12 value=0.45;
        set plane Z=13 value=0.45;
        set plane Z=14 value=0.45;
        set plane Z=15 value=0.45;
      </scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Final Branch Interval Plant 71 RootOrder1</characteristic>
      <scheme>set scoreboard value=1.5;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Final Branch Interval Plant 71 RootOrder2</characteristic>
      <scheme>set scoreboard value=0.6;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Final Branch Interval Plant 71 RootOrder>=3</characteristic>
      <scheme>set scoreboard value=0.6;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Geotropism Index Plant 71 RootOrder0</characteristic>
      <scheme>set scoreboard value=0.75;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Geotropism Index Plant 71 RootOrder1</characteristic>
      <scheme>set scoreboard value=0.2;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Geotropism Index Plant 71 RootOrder2</characteristic>
      <scheme>set scoreboard value=0.1;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Geotropism Index Plant 71 RootOrder>=3</characteristic>
      <scheme>set scoreboard value=0.1;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Deflection Index Plant 71 RootOrder0</characteristic>
      <scheme>set scoreboard value=0.25;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Deflection Index Plant 71 RootOrder1</characteristic>
      <scheme>set scoreboard value=0.2;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Deflection Index Plant 71 RootOrder2</characteristic>
      <scheme>set scoreboard value=0.2;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Seminal Deflection Index Plant 71 RootOrder>=3</characteristic>
      <scheme>set scoreboard value=0.2;</scheme>
    </scoreboarddata>
  </initialisation>
</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Wheat with compaction/shared_attributes/PlantAttributeInitialValues.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<rootmap
        xmlns="https://example.org/ROOTMAP/ScoreboardDataSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ScoreboardDataSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/ScoreboardData.xsd">
  <initialisation>
    <owner>Scoreboard</owner>
    <!-- Plant SharedAttributes -->
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Growth Rate Max Plant 1 RootOrder0 VolumeObject 1</characteristic>
      <scheme>set scoreboard value=0.02;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Growth Rate Max Plant 1 RootOrder1 VolumeObject 1</characteristic>
      <scheme>set scoreboard value=0.006;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Growth Rate Max Plant 1 RootOrder2 VolumeObject 1</characteristic>
      <scheme>set scoreboard value=0.005;</scheme>
    </scoreboarddata>
    <scoreboarddata>
      <process>PlantCoordinator</process>
      <characteristic>Growth Rate Max Plant 1 RootOrder>=3 VolumeObject 1</characteristic>
      <scheme>set scoreboard value=0.003;</scheme>
    </scoreboarddata>
  </initialisation>
</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/default/scoreboard_data/BulkDensity.xml
<?xml version="1.0" encoding="utf-8"?>
<rootmap
        xmlns="https://example.org/ROOTMAP/ScoreboardDataSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ScoreboardDataSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/ScoreboardData.xsd">
    <initialisation>
        <owner>Scoreboard</owner>
        <scoreboarddata>
            <!-- Bulk Density g/cm3, same for both the Yellow Sand and the Vetosol Soil simulations -->
            <process>Bulk Density</process>
            <characteristic>Bulk Density VolumeObject [none]</characteristic>
            <scheme>
        set scoreboard value=1.0;
            </scheme>
        </scoreboarddata>
        <scoreboarddata>
            <!-- Bulk Density g/cm3, same for both the Yellow Sand and the Vetosol Soil simulations -->
            <process>Bulk Density</process>
            <characteristic>Bulk Density VolumeObject 1</characteristic>
            <scheme>
        set scoreboard value=1.0;
            </scheme>
        </scoreboarddata>
    </initialisation>
</rootmap>
