=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/Scoreboards.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/ScoreboardsSchema"
           targetNamespace="https://example.org/ROOTMAP/ScoreboardsSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:annotation>
                <xsd:documentation>Defines boundaries of Scoreboard layers.</xsd:documentation>
            </xsd:annotation>
            <xsd:sequence>
                <xsd:element type="tns:Construction" name="construction" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Construction">
        <xsd:sequence>
            <xsd:element type="xsd:string" name="owner"/>
            <xsd:element type="tns:Scoreboard" name="scoreboard" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Scoreboard">
        <xsd:sequence>
            <xsd:element type="xsd:string" name="name" />
            <xsd:element type="xsd:int" name="stratum" />
            <xsd:element type="tns:BoundaryArray" name="boundaryarray" minOccurs="3" maxOccurs="3"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="BoundaryArray">
        <xsd:sequence>
            <xsd:element type="tns:Dimension" name="dimension"/>
            <xsd:element type="tns:PositionArray" name="positionarray" />
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Wheat with compaction/Scoreboards.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!-- Scoreboard layers' boundaries file                                     -->
<!--                                                                        -->
<!-- FORMAT:XML                                                             -->
<!--                                                                        -->
<!-- NO C-style comments                                                    -->
<!--                                                                        -->
<rootmap
        xmlns="https://example.org/ROOTMAP/ScoreboardsSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ScoreboardsSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/Scoreboards.xsd">
  <construction>
    <owner>ScoreboardCoordinator</owner>
    <scoreboard>
      <name>
        Soil
      </name>
      <stratum>
        2
      </stratum>
      <boundaryarray>
        <dimension>X</dimension>
        <!-- NOTE that the positionarray does not have any  -->
        <!-- whitespace between the first and last elements,0,1,2,3,4,5,6,7,8,9,10-->
        <!-- only commas                     -->
        <positionarray>
          0,2,4,6,8,10,12,14,16,18,20,22,24
        </positionarray>
      </boundaryarray>
      <boundaryarray>
        <dimension>Y</dimension>
        <positionarray>
          0,2,4,6,8,10,12,14,16,18,20,22,24
        </positionarray>
      </boundaryarray>
      <boundaryarray>
        <dimension>Z</dimension>
        <positionarray>
          0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40
        </positionarray>
      </boundaryarray>
    </scoreboard>
  </construction>
</rootmap>
