=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/ScoreboardData.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/ScoreboardDataSchema"
           targetNamespace="https://example.org/ROOTMAP/ScoreboardDataSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="initialisation" type="tns:ScoreboardData" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="ScoreboardData">
        <xsd:sequence>
            <xsd:element name="owner" type="xsd:string" fixed="Scoreboard" />
            <xsd:element name="scoreboarddata" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="process" type="xsd:string" />
                        <xsd:element name="characteristic" type="xsd:string" />
                        <!-- TODO restrict to valid scheme definitions? -->
                        <xsd:element name="scheme" type="xsd:string" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Genotype 44 Soil config/scoreboard_data/PhosphorusData.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Soil P for modelling lupin root growth in pots, simulations in sandy soil -->
<rootmap
        xmlns="https://example.org/ROOTMAP/ScoreboardDataSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ScoreboardDataSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/ScoreboardData.xsd">
  <initialisation>
    <owner>Scoreboard</owner>
    <scoreboarddata>
      <!-- Added P µgP/g soil, top dressed fertiliser = P mixed through the top 3cm of soil -->-->
      <process>Phosphorus</process>
      <characteristic>Added P</characteristic>
      <scheme>
        set scoreboard value=0.0;
        set plane Z=1 value=399.8;
        set plane Z=2 value=399.8;
        set plane Z=3 value=399.8;
      </scheme>
    </scoreboarddata>
  </initialisation>

  <initialisation>
    <owner>Scoreboard</owner>
    <scoreboarddata>
      <process>Phosphorus</process>
      <!-- Total Labile P µgP/g in each soil cube, or µgP/mL for nutrient solution simulations-->
      <characteristic>Total Labile P</characteristic>
      <scheme>
        set scoreboard value=8.0;
      </scheme>
    </scoreboarddata>
  </initialisation>
</rootmap>
