=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/SharedAttributes.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/SharedAttributesSchema"
           targetNamespace="https://example.org/ROOTMAP/SharedAttributesSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="construction" type="tns:SharedAttributes" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="SharedAttributes">
        <xsd:sequence>
            <xsd:element name="owner" type="xsd:string" fixed="SharedAttributeManager" />
            <xsd:element name="attribute" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="owner" type="xsd:string" />
                        <xsd:element name="characteristic_descriptor" type="tns:Characteristic" />
                        <xsd:element name="storage" type="xsd:string" />
                        <xsd:element name="variations">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:pattern value="([a-zA-Z]+,)*[a-zA-Z]*"/>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>
                        <xsd:element name="defaults" type="tns:Defaults" minOccurs="0" />

                        <xsd:element name="values" minOccurs="0">
                            <xsd:simpleType>
                                <xsd:annotation>
                                    <xsd:documentation>Comma-separated list of per-variation default values.
                                    </xsd:documentation>
                                </xsd:annotation>
                                <xsd:restriction base="xsd:string">
                                    <xsd:pattern value="([0-9]+(\.[0-9]+)?,)*[0-9]+(\.[0-9]+)?"/>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Characteristic">
        <xsd:all>
            <xsd:element name="minimum" type="xsd:double">
                <xsd:annotation>
                    <xsd:documentation>Supports scientific notation and the special values INF (infinity), -INF (negative infinity) an NaN (not a number).
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="maximum" type="xsd:double">
                <xsd:annotation>
                    <xsd:documentation>Supports scientific notation and the special values INF (infinity), -INF (negative infinity) an NaN (not a number).
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="default" type="xsd:double">
                <xsd:annotation>
                    <xsd:documentation>Supports scientific notation and the special values INF (infinity), -INF (negative infinity) an NaN (not a number).
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="units" type="xsd:string" />
            <xsd:element name="visible" type="xsd:boolean" />
            <xsd:element name="editable" type="xsd:boolean" />
            <xsd:element name="tobesaved" type="xsd:boolean" />
            <xsd:element name="specialperboxinfo" type="xsd:boolean" minOccurs="0" />
            <xsd:element name="stratum" type="xsd:string" minOccurs="0" />
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="Defaults">
        <xsd:sequence>
            <xsd:element name="variation_name" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Must reference a variation from the variations element of this attribute.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="values">
                <xsd:simpleType>
                    <xsd:annotation>
                        <xsd:documentation>Comma-separated list of per-variation default values.
                        </xsd:documentation>
                    </xsd:annotation>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="([0-9]+(\.[0-9]+)?,)*[0-9]+(\.[0-9]+)?"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Genotype 120 Soil config/shared_attributes/WaterAttributes.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rootmap
        xmlns="https://example.org/ROOTMAP/SharedAttributesSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/SharedAttributesSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/SharedAttributes.xsd">
  <construction>
    <owner>SharedAttributeManager</owner>
    <attribute>
      <owner>Water</owner>
      <characteristic_descriptor>
        <name>Water Flux</name>
        <units>cm^3/cm s</units>
        <minimum>0.0</minimum>
        <maximum>1000.0</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
            <variations>Plant,RootOrder,VolumeObject</variations>
    </attribute>
    <attribute>
      <owner>Water</owner>
      <characteristic_descriptor>
        <name>Cumul Local Plant Water Uptake</name>
        <units>cm^3</units>
        <minimum>0.0</minimum>
        <maximum>1000.0</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
            <variations>Plant,VolumeObject</variations>
    </attribute>
	<attribute>
	  <owner>Water</owner>
	  <characteristic_descriptor>
		<name>Water Upregulation Limit</name>
		<units>[None]</units>
		<minimum>1.0</minimum>
		<maximum>3.0</maximum>
		<default>1.2</default>
		<visible>false</visible>
		<editable>false</editable>
		<tobesaved>true</tobesaved>
		<specialperboxinfo>false</specialperboxinfo>
		<stratum>Soil</stratum>
	  </characteristic_descriptor>
	  <storage>Water</storage>
	  <variations>Plant</variations>
	</attribute>
	<attribute>
	  <owner>Water</owner>
	  <characteristic_descriptor>
		<name>Cumul Total Plant Water Uptake</name>
	    <units>cm^3</units>
		<minimum>0.0</minimum>
		<maximum>1.0e10</maximum>
		<default>0.0</default>
		<visible>true</visible>
		<editable>true</editable>
		<tobesaved>true</tobesaved>
		<specialperboxinfo>false</specialperboxinfo>
		<stratum>Soil</stratum>
	  </characteristic_descriptor>
	  <storage>Water</storage>
	  <variations>Plant</variations>
	  </attribute>
	  <attribute>
		  <owner>Water</owner>
		  <characteristic_descriptor>
			  <name>Local Plant Water Uptake</name>
			  <units>cm^3</units>
			  <minimum>0.0</minimum>
			  <maximum>1.0e10</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>true</editable>
			  <tobesaved>true</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Scoreboard</storage>
            <variations>Plant,VolumeObject</variations>
	  </attribute>	  
	  <attribute>
		  <owner>Water</owner>
		  <characteristic_descriptor>
			  <name>Rain Amount</name>
			  <units>cm</units>
			  <minimum>0.0</minimum>
			  <maximum>1.0e10</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>true</editable>
			  <tobesaved>true</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Water</storage>
            <variations/>
	  </attribute>
	  <attribute>
		  <owner>Water</owner>
		  <characteristic_descriptor>
			  <name>Pan Evaporation</name>
			  <units>mm</units>
			  <minimum>0.0</minimum>
			  <maximum>1.0e10</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>true</editable>
			  <tobesaved>true</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Water</storage>
            <variations/>
	  </attribute>
	  <attribute>
		  <owner>Water</owner>
		  <characteristic_descriptor>
			  <name>Max Temperature</name>
			  <units>&#xB0;</units>
			  <minimum>0.0</minimum>
			  <maximum>1.0e10</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>true</editable>
			  <tobesaved>true</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Water</storage>
            <variations/>
	  </attribute>	  
	  <attribute>
		  <owner>Water</owner>
		  <characteristic_descriptor>
			  <name>Min Temperature</name>
			  <units>&#xB0;</units>
			  <minimum>0.0</minimum>
			  <maximum>1.0e10</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>true</editable>
			  <tobesaved>true</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Water</storage>
            <variations/>
	  </attribute>
	  <attribute>
		  <owner>Water</owner>
		  <characteristic_descriptor>
			  <name>Radiation</name>
			  <units>MJm^-2</units>
			  <minimum>0.0</minimum>
			  <maximum>1.0e10</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>true</editable>
			  <tobesaved>true</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Water</storage>
            <variations/>
	  </attribute>
	  <attribute>
		  <owner>Water</owner>
		  <characteristic_descriptor>
			  <name>Green Cover</name>
			  <units>NONE</units>
			  <minimum>0.0</minimum>
			  <maximum>1.0</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>true</editable>
			  <tobesaved>true</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Water</storage>
            <variations/>
	  </attribute>
    <attribute>
      <owner>Water</owner>
      <characteristic_descriptor>
        <name>Avg Green Cover Factor</name>
        <units>NONE</units>
        <minimum>0.0</minimum>
        <maximum>1.0</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Water</storage>
            <variations/>
    </attribute>
	  <attribute>
		  <owner>Water</owner>
		  <characteristic_descriptor>
			  <name>Residue Cover</name>
			  <units>NONE</units>
			  <minimum>0.0</minimum>
			  <maximum>1.0</maximum>
			  <default>0.1</default>
			  <visible>true</visible>
			  <editable>true</editable>
			  <tobesaved>true</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Water</storage>
            <variations/>
	  </attribute>
	  <attribute>
		  <owner>Water</owner>
		  <characteristic_descriptor>
			  <name>Cumulative Evaporation Before Germination</name>
			  <units>mm</units>
			  <minimum>0.0</minimum>
			  <maximum>1.0e10</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>true</editable>
			  <tobesaved>true</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Water</storage>
            <variations/>
	  </attribute>
	  <attribute>
		  <owner>Water</owner>
		  <characteristic_descriptor>
			  <name>Cumulative Evaporation After Germination</name>
			  <units>mm</units>
			  <minimum>0.0</minimum>
			  <maximum>1.0e10</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>true</editable>
			  <tobesaved>true</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Water</storage>
            <variations/>
	  </attribute>
    <attribute>
      <owner>Water</owner>
      <characteristic_descriptor>
        <!-- Tell the water routine whether to calculate evaporation or not 0 = don't calculate; 1 = do calculate -->
        <name>Calculate Evaporation</name>
        <units>unitless</units>
        <minimum>0.0</minimum>
        <maximum>1.0</maximum>
        <default>0.0</default>
        <visible>false</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Water</storage>
            <variations/>
    </attribute>
	  
  </construction>
</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Genotype 44 Soil config/old_shared_attributes/PlantAttributes.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<rootmap
        xmlns="https://example.org/ROOTMAP/SharedAttributesSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/SharedAttributesSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/SharedAttributes.xsd">
  <construction>
    <owner>SharedAttributeManager</owner>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Branch Lag Time</name>
        <units>hours</units>
        <minimum>0.0</minimum>
        <maximum>infinity</maximum>
        <default>150.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>RootOrder</variations>
      <defaults>
        <variation_name>RootOrder</variation_name>
        <defaults>96.0,96.0,360.0,480.0</defaults>
      </defaults>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Deflection Index</name>
        <units>-</units>
        <minimum>0.0</minimum>
        <maximum>1.0</maximum>
        <default>0.3</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>RootOrder</variations>
      <defaults>
        <variation_name>RootOrder</variation_name>
        <defaults>0.3,0.25,0.25,0.25</defaults>
      </defaults>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Final Branch Interval</name>
        <units>cm</units>
        <minimum>0.0</minimum>
        <maximum>10.0</maximum>
        <default>2.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>RootOrder</variations>
      <defaults>
        <variation_name>RootOrder</variation_name>
        <defaults>0.5,0.6,0.5,0.4</defaults>
      </defaults>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Geotropism Index</name>
        <units>-</units>
        <minimum>0.0</minimum>
        <maximum>1.0</maximum>
        <default>0.8</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>RootOrder</variations>
      <defaults>
        <variation_name>RootOrder</variation_name>
        <defaults>0.8,0.15,0.0,0.0</defaults>
      </defaults>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Growth Rate Max</name>
        <units>cm/hour</units>
        <minimum>0.0</minimum>
        <maximum>10.0</maximum>
        <default>0.5</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>Plant,RootOrder</variations>
      <defaults>
        <variation_name>RootOrder</variation_name>
        <defaults>0.4,0.4,0.4,0.4</defaults>
      </defaults>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Initial Branch Angle</name>
        <units>&#xB0;</units>
        <minimum>0.0</minimum>
        <maximum>180.0</maximum>
        <default>90.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>RootOrder</variations>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Initial Branch Interval</name>
        <units>cm</units>
        <minimum>0.0</minimum>
        <maximum>100.0</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>RootOrder</variations>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Root Conductance</name>
        <units>-</units>
        <minimum>0.0</minimum>
        <maximum>1.0</maximum>
        <default>1.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>RootOrder</variations>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Tip Growth Duration</name>
        <units>hours</units>
        <minimum>0.0</minimum>
        <maximum>infinity</maximum>
        <default>6000.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>RootOrder</variations>
      <defaults>
        <variation_name>RootOrder</variation_name>
        <defaults>6000,3120,1920,1776</defaults>
      </defaults>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Initial Seminal Deflection</name>
        <units>&#xB0;</units>
        <minimum>0.0</minimum>
        <maximum>90.0</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>PlantCoordinator</storage>
      <variations>PlantType</variations>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Germination Lag</name>
        <units>hours</units>
        <minimum>0.0</minimum>
        <maximum>infinity</maximum>
        <default>27.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>PlantCoordinator</storage>
      <variations>PlantType</variations>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>First Seminal Probability</name>
        <units>-</units>
        <minimum>0.0</minimum>
        <maximum>1.0</maximum>
        <default>1.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>PlantCoordinator</storage>
      <variations>PlantType</variations>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Temperature of Zero Growth</name>
        <units>&#xB0;</units>
        <minimum>-infinity</minimum>
        <maximum>infinity</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>PlantCoordinator</storage>
      <variations>PlantType</variations>
    </attribute>
    <attribute>
      <owner>PlantCoordinator</owner>
      <characteristic_descriptor>
        <name>Root Radius</name>
        <units>mm</units>
        <minimum>0.01</minimum>
        <maximum>5.0</maximum>
        <default>1.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>PlantCoordinator</storage>
      <variations>Plant,RootOrder</variations>
    </attribute>
      <attribute>
        <owner>PlantCoordinator</owner>
        <characteristic_descriptor>
          <name>Organic Exudate</name>
          <units>none</units>
          <!-- none = 0, lecithin = 1, citrate = 2, malate = 3 -->
          <minimum>0</minimum>
          <maximum>3</maximum>
          <default>1</default>
          <visible>true</visible>
          <editable>true</editable>
          <tobesaved>true</tobesaved>
          <stratum>Soil</stratum>
        </characteristic_descriptor>
        <storage>PlantCoordinator</storage>
        <variations>Plant</variations>
      </attribute>
  </construction>
</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Genotype 44 Soil config/old_shared_attributes/NitrateAttributes.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<rootmap
        xmlns="https://example.org/ROOTMAP/SharedAttributesSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/SharedAttributesSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/SharedAttributes.xsd">
  <construction>
    <owner>SharedAttributeManager</owner>

    <attribute>
      <owner>Nitrate</owner>
      <characteristic_descriptor>
        <name>Plant Nitrate Uptake</name>
        <units>mols</units>
        <minimum>0.0</minimum>
        <maximum>INF</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Nitrate</storage>
      <variations>Plant</variations>
    </attribute>

    <attribute>
      <owner>Nitrate</owner>
      <characteristic_descriptor>
        <name>RO Nitrate Uptake</name>
        <units>mols</units>
        <minimum>0.0</minimum>
        <maximum>INF</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Nitrate</storage>
      <variations>RootOrder</variations>
    </attribute>

    <attribute>
      <owner>Nitrate</owner>
      <characteristic_descriptor>
        <name>Total Nitrate Uptake</name>
        <units>mols</units>
        <minimum>0.0</minimum>
        <maximum>INF</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Nitrate</storage>
    </attribute>

  </construction>
</rootmap>
