=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/SharedAttributes.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/SharedAttributesSchema"
           targetNamespace="https://example.org/ROOTMAP/SharedAttributesSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="construction" type="tns:SharedAttributes" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="SharedAttributes">
        <xsd:sequence>
            <xsd:element name="owner" type="xsd:string" fixed="SharedAttributeManager" />
            <xsd:element name="attribute" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="owner" type="xsd:string" />
                        <xsd:element name="characteristic_descriptor" type="tns:Characteristic" />
                        <xsd:element name="storage" type="xsd:string" />
                        <xsd:element name="variations">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:pattern value="([a-zA-Z]+,)*[a-zA-Z]*"/>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>
                        <xsd:element name="defaults" type="tns:Defaults" minOccurs="0" />

                        <xsd:element name="values" minOccurs="0">
                            <xsd:simpleType>
                                <xsd:annotation>
                                    <xsd:documentation>Comma-separated list of per-variation default values.
                                    </xsd:documentation>
                                </xsd:annotation>
                                <xsd:restriction base="xsd:string">
                                    <xsd:pattern value="([0-9]+(\.[0-9]+)?,)*[0-9]+(\.[0-9]+)?"/>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Characteristic">
        <xsd:all>
            <xsd:element name="minimum" type="xsd:double">
                <xsd:annotation>
                    <xsd:documentation>Supports scientific notation and the special values INF (infinity), -INF (negative infinity) an NaN (not a number).
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="maximum" type="xsd:double">
                <xsd:annotation>
                    <xsd:documentation>Supports scientific notation and the special values INF (infinity), -INF (negative infinity) an NaN (not a number).
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="default" type="xsd:double">
                <xsd:annotation>
                    <xsd:documentation>Supports scientific notation and the special values INF (infinity), -INF (negative infinity) an NaN (not a number).
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="units" type="xsd:string" />
            <xsd:element name="visible" type="xsd:boolean" />
            <xsd:element name="editable" type="xsd:boolean" />
            <xsd:element name="tobesaved" type="xsd:boolean" />
            <xsd:element name="specialperboxinfo" type="xsd:boolean" minOccurs="0" />
            <xsd:element name="stratum" type="xsd:string" minOccurs="0" />
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="Defaults">
        <xsd:sequence>
            <xsd:element name="variation_name" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Must reference a variation from the variations element of this attribute.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="values">
                <xsd:simpleType>
                    <xsd:annotation>
                        <xsd:documentation>Comma-separated list of per-variation default values.
                        </xsd:documentation>
                    </xsd:annotation>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="([0-9]+(\.[0-9]+)?,)*[0-9]+(\.[0-9]+)?"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/config_Genotype85/shared_attributes/PhosphorusAttributes.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rootmap
        xmlns="https://example.org/ROOTMAP/SharedAttributesSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/SharedAttributesSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/SharedAttributes.xsd">
  <construction>
    <owner>SharedAttributeManager</owner>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <name>Phosphorus Uptake</name>
        <units>µmol</units>
        <minimum>0.0</minimum>
        <maximum>1000000.0</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>Plant,VolumeObject</variations>
    </attribute>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <name>Cumulative Phosphorus Uptake</name>
        <units>µgP</units>
        <minimum>0.0</minimum>
        <maximum>1000000.0</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Phosphorus</storage>
      <variations>Plant</variations>
    </attribute>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <name>Cumulative Fertiliser P Uptake</name>
        <units>µgP</units>
        <minimum>0.0</minimum>
        <maximum>1000000.0</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Phosphorus</storage>
      <variations>Plant</variations>
    </attribute>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <name>Cumul Local Phosphorus Uptake</name>
        <units>µgP</units>
        <minimum>0.0</minimum>
        <maximum>1000.0</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>Plant,VolumeObject</variations>
    </attribute>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <name>P Absorption Power</name>
        <units>cm/s</units>
        <minimum>0.0</minimum>
        <maximum>1e-3</maximum>
        <default>4e-4</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>Plant,VolumeObject</variations>
    </attribute>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <name>Organic P Mineralisation</name>
        <units>none</units>
        <minimum>0</minimum>
        <maximum>1</maximum>
        <default>0</default>
        <visible>false</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Phosphorus</storage>
      <variations>Plant</variations>
    </attribute>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <name>Org P Min Fraction</name>
        <units>none</units>
        <minimum>0</minimum>
        <maximum>1</maximum>
        <default>0.003</default>
        <visible>false</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Phosphorus</storage>
      <variations>Plant</variations>
    </attribute>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <name>Org P Min Time</name>
        <units>months</units>
        <minimum>1</minimum>
        <maximum>12</maximum>
        <default>10</default>
        <visible>false</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Phosphorus</storage>
      <variations>Plant</variations>
    </attribute>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <name>P Utilisation Efficiency</name>
        <units>unitless</units>
        <minimum>0.0</minimum>
        <maximum>10.0</maximum>
        <default>1.0</default>
        <visible>false</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Phosphorus</storage>
      <variations>Plant</variations>
    </attribute>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <name>P Flux Max</name>
        <units>umols/cm.s</units>
        <minimum>0.0</minimum>
        <maximum>0.01</maximum>
        <default>0.9e-8</default>
        <visible>false</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Phosphorus</storage>
      <variations>Plant</variations>
    </attribute>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <name>P Uptake Kinetic Const</name>
        <units>umols/cm3</units>
        <minimum>0.0</minimum>
        <maximum>1.0</maximum>
        <default>0.0055</default>
        <visible>false</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Phosphorus</storage>
      <variations>Plant</variations>
    </attribute>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <name>P Conc Min</name>
        <units>umols/cm3</units>
        <minimum>0.0</minimum>
        <maximum>0.1</maximum>
        <default>0.0002</default>
        <visible>false</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Phosphorus</storage>
      <variations>Plant</variations>
    </attribute>
    <attribute>
      <owner>Phosphorus</owner>
      <characteristic_descriptor>
        <minimum>0.0</minimum>
        <maximum>5.0</maximum>
        <default>1.0</default>
        <name>Apase Multiplier</name>
        <units>none</units>
        <visible>false</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Phosphorus</storage>
      <variations></variations>
    </attribute>
  </construction>
</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/config_Genotype85/shared_attributes/NitrateAttributes.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<rootmap
        xmlns="https://example.org/ROOTMAP/SharedAttributesSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/SharedAttributesSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/SharedAttributes.xsd">
	<construction>
	<owner>SharedAttributeManager</owner>

    <attribute>
      <owner>Nitrate</owner>
      <characteristic_descriptor>
        <name>Plant Nitrate Uptake</name>
        <units>µmols</units>
        <minimum>0.0</minimum>
        <maximum>INF</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>Plant,VolumeObject</variations>
    </attribute>
    <attribute>
      <owner>Nitrate</owner>
      <characteristic_descriptor>
        <name>Cumul Plant N Fixation</name>
        <units>µmols</units>
        <minimum>0.0</minimum>
        <maximum>INF</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Nitrate</storage>
      <variations>Plant</variations>
    </attribute>
	  <attribute>
		  <owner>Nitrate</owner>
		  <characteristic_descriptor>
			  <name>Cumul Plant Nitrate Uptake</name>
			  <units>µgN</units>
			  <minimum>0.0</minimum>
			  <maximum>INF</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>false</editable>
			  <tobesaved>false</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Nitrate</storage>
		  <variations>Plant</variations>
	  </attribute>
	  <attribute>
		  <owner>Nitrate</owner>
		  <characteristic_descriptor>
			  <name>Cumul Plant FertN Uptake</name>
			  <units>µgN</units>
			  <minimum>0.0</minimum>
			  <maximum>INF</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>false</editable>
			  <tobesaved>false</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Nitrate</storage>
		  <variations>Plant</variations>
	  </attribute>
    <attribute>
      <owner>Nitrate</owner>
      <characteristic_descriptor>
        <name>Cumul RO Nitrate Uptake</name>
        <units>µgN</units>
        <minimum>0.0</minimum>
        <maximum>INF</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Nitrate</storage>
      <variations>Plant,RootOrder,VolumeObject</variations>
    </attribute>
    <attribute>
      <owner>Nitrate</owner>
      <characteristic_descriptor>
        <name>Cumul Local Nitrate Uptake</name>
        <units>µgN</units>
        <minimum>0.0</minimum>
        <maximum>INF</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
	  <variations>Plant,VolumeObject</variations>
    </attribute>
	  <attribute>
		  <owner>Nitrate</owner>
		  <characteristic_descriptor>
			  <name>Cumul Local FertN Uptake</name>
			  <units>µgN</units>
			  <minimum>0.0</minimum>
			  <maximum>INF</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>false</editable>
			  <tobesaved>false</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Scoreboard</storage>
		  <variations>Plant,VolumeObject</variations>
	  </attribute>
	  <attribute>
		  <owner>Nitrate</owner>
		  <characteristic_descriptor>
			  <name>Added Fertiliser N</name>
        <!-- days after sowing that the 2nd N fertiliser application is made -->
			  <units>days</units>
			  <minimum>0.0</minimum>
			  <maximum>360</maximum>
			  <default>0.0</default>
			  <visible>true</visible>
			  <editable>false</editable>
			  <tobesaved>false</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Nitrate</storage>
		  <variations>Plant</variations>
	  </attribute>
	  <attribute>
		  <owner>Nitrate</owner>
		  <characteristic_descriptor>
			  <name>N Absorption Power</name>
			  <units>cm/s</units>
			  <minimum>1e-9</minimum>
			  <maximum>1e-3</maximum>
			  <default>2e-7</default>
			  <visible>true</visible>
			  <editable>false</editable>
			  <tobesaved>false</tobesaved>
			  <specialperboxinfo>false</specialperboxinfo>
			  <stratum>Soil</stratum>
		  </characteristic_descriptor>
		  <storage>Nitrate</storage>
		  <variations>Plant,VolumeObject</variations>
	  </attribute>
    <attribute>
      <owner>Nitrate</owner>
      <characteristic_descriptor>
        <name>N Flux Max</name>
        <units>umol/cm.s</units>
        <minimum>0.0</minimum>
        <maximum>0.01</maximum>
        <default>9.5e-7</default>
        <visible>false</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Nitrate</storage>
      <variations>Plant</variations>
    </attribute>
    <attribute>
      <owner>Nitrate</owner>
      <characteristic_descriptor>
        <name>N Uptake Kinetic Const</name>
        <units>umol/cm3</units>
        <minimum>0.0</minimum>
        <maximum>1.0</maximum>
        <default>0.01188</default>
        <visible>false</visible>
        <editable>false</editable>
        <tobesaved>false</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Nitrate</storage>
      <variations>Plant</variations>
    </attribute>
    		<attribute>
			<owner>Nitrate</owner>
			<characteristic_descriptor>
				<name>Degree Days</name>
				<units>&#xB0;&#xB0;</units>
				<minimum>0.0</minimum>
				<maximum>1.0e10</maximum>
				<default>0.0</default>
				<visible>true</visible>
				<editable>true</editable>
				<tobesaved>true</tobesaved>
				<specialperboxinfo>false</specialperboxinfo>
				<stratum>Soil</stratum>
			</characteristic_descriptor>
			<storage>Nitrate</storage>
			<variations></variations>
		</attribute>
		<attribute>
			<owner>Nitrate</owner>
			<characteristic_descriptor>
				<name>Degree Days at Growth Start</name>
				<units>&#xB0;days</units>
				<minimum>0.0</minimum>
				<maximum>1.0e10</maximum>
				<default>0.0</default>
				<visible>true</visible>
				<editable>true</editable>
				<tobesaved>true</tobesaved>
				<specialperboxinfo>false</specialperboxinfo>
				<stratum>Soil</stratum>
			</characteristic_descriptor>
			<storage>Nitrate</storage>
			<variations></variations>
		</attribute>
		<attribute>
			<owner>Nitrate</owner>
			<characteristic_descriptor>
				<minimum>0</minimum>
				<maximum>100</maximum>
				<default>10.0</default>
				<name>Mineralisation Depth</name>
				<units>cm</units>
				<visible>true</visible>
				<editable>true</editable>
				<tobesaved>true</tobesaved>
				<specialperboxinfo>false</specialperboxinfo>
				<stratum>Soil</stratum>
			</characteristic_descriptor>
			<storage>Nitrate</storage>
			<variations></variations>
		</attribute>
    <attribute>
      <owner>Nitrate</owner>
      <characteristic_descriptor>
        <minimum>0</minimum>
        <maximum>100</maximum>
        <default>0.0</default>
        <name>Calculate Nitrate Mineralisation</name>
        <units>none</units>
        <visible>false</visible>
        <editable>false</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Nitrate</storage>
      <variations></variations>
    </attribute>
  </construction>
</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Genotype 60 Soil config/old_shared_attributes/WaterAttributes.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rootmap
        xmlns="https://example.org/ROOTMAP/SharedAttributesSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/SharedAttributesSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/SharedAttributes.xsd">
  <construction>
    <owner>SharedAttributeManager</owner>
    <attribute>
      <owner>Water</owner>
      <characteristic_descriptor>
        <name>Water Flux</name>
        <units>cm^3/cm s</units>
        <minimum>0.0</minimum>
        <maximum>1000.0</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>Plant,RootOrder</variations>
    </attribute>
    <attribute>
      <owner>Water</owner>
      <characteristic_descriptor>
        <name>Water Uptake</name>
        <units>cm^3</units>
        <minimum>0.0</minimum>
        <maximum>1000.0</maximum>
        <default>0.0</default>
        <visible>true</visible>
        <editable>true</editable>
        <tobesaved>true</tobesaved>
        <specialperboxinfo>false</specialperboxinfo>
        <stratum>Soil</stratum>
      </characteristic_descriptor>
      <storage>Scoreboard</storage>
      <variations>Plant</variations>
    </attribute>
  </construction>
</rootmap>
