=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/VolumeObjects.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/VolumeObjectsSchema"
           targetNamespace="https://example.org/ROOTMAP/VolumeObjectsSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element type="tns:Construction" name="construction" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Construction">
        <xsd:sequence>
            <xsd:element type="xsd:string" name="owner" fixed="VolumeObjectCoordinator" />
            <xsd:element type="tns:VolumeObject" name="volumeobject" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="VolumeObject">
        <xsd:sequence>
            <xsd:element name="class_name" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="BoundingCylinder" />
                        <xsd:enumeration value="BoundingRectangularPrism" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="root_penetration_probability" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element type="tns:UnitInterval" name="top" maxOccurs="1"/>
                        <xsd:element type="tns:UnitInterval" name="bottom" maxOccurs="1"/>
                        <xsd:element type="tns:UnitInterval" name="sides" maxOccurs="1"/>
                        <xsd:element name="probability_calculation_algorithm">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:enumeration value="Directly Specified" />
                                    <xsd:enumeration value="Cosin Proportional" />
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="permeability" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element type="tns:UnitInterval" name="top" maxOccurs="1"/>
                        <xsd:element type="tns:UnitInterval" name="bottom" maxOccurs="1"/>
                        <xsd:element type="tns:UnitInterval" name="sides" maxOccurs="1"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <!-- TODO <choice></choice> of sequences here -->
            <xsd:element name="origin" type="tns:Coordinate3D" minOccurs="0" />
            <xsd:element name="depth" type="xsd:decimal" minOccurs="0" />
            <xsd:element name="radius" type="tns:PositiveDecimal" minOccurs="0" />
            <xsd:element name="leftfronttop" type="tns:Coordinate3D" minOccurs="0" />
            <xsd:element name="rightbackbottom" type="tns:Coordinate3D" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Wheat with compaction/VolumeObjects.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<!-- VolumeObject specification file                                        -->
<!--                                                                        -->
<!-- FORMAT:XML                                                             -->
<!--                                                                        -->
<!-- NO C-style comments                                                    -->
<!--                                                                        -->
<!-- CURRENTLY SUPPORTED CLASSES:                                           -->
<!--                                                                        -->
<!-- BoundingCylinder                                                       -->
<!-- Specifies a cylinder of a given depth, 								-->
<!-- the top disc centred at the coordinate <origin>.  						-->
<!-- BoundingCylinders have impenetrable surfaces and do not affect         -->
<!-- the growth rate of root tips growing within them.                      -->
<!--<rootmap
        xmlns="https://example.org/ROOTMAP/VolumeObjectsSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/VolumeObjectsSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/VolumeObjects.xsd">
  <construction>
    <owner>VolumeObjectCoordinator</owner>
    <volumeobject>
      <class_name>BoundingCylinder</class_name>
      <origin>5.0,5.0,0</origin>
      <depth>50.0</depth>
      <radius>5.0</radius>
    </volumeobject>
  </construction>
</rootmap>                                                                  -->
<!-- BoundingRectangularPrism                                               -->
<!-- Specifies a right cuboid defined by two points, the left front top     -->
<!-- and right back bottom coordinates. Aligned with the Z-axis             -->
<!-- in the same way as BoundingCylinders.                                  -->
<!-- BoundingRectangularPrisms have impenetrable surfaces and do not affect -->
<!-- the growth rate of root tips growing within them.                      -->
<!--  <rootmap
        xmlns="https://example.org/ROOTMAP/VolumeObjectsSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/VolumeObjectsSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/VolumeObjects.xsd">
    <construction>
     <owner>VolumeObjectCoordinator</owner>
     <volumeobject>
        <class_name>BoundingRectangularPrism</class_name>
       <leftfronttop>0,0,0</leftfronttop>
       <rightbackbottom>16,1,120</rightbackbottom>
      </volumeobject>
   </construction>
  </rootmap>
		<leftfronttop>1.9,1.9,1.9</leftfronttop>
		<rightbackbottom>4,4,6</rightbackbottom>
-->

<rootmap
        xmlns="https://example.org/ROOTMAP/VolumeObjectsSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/VolumeObjectsSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/VolumeObjects.xsd">
  <construction>
    <owner>VolumeObjectCoordinator</owner>
	  <volumeobject>
      <class_name>BoundingRectangularPrism</class_name>
      <root_penetration_probability>
        <top>0.1</top>
        <bottom>1.0</bottom>
        <sides>0.0</sides>
        <probability_calculation_algorithm>Directly Specified</probability_calculation_algorithm>
      </root_penetration_probability>
      <permeability>
        <top>0.0</top>
        <bottom>0.0</bottom>
        <sides>0.0</sides>
      </permeability>
      <leftfronttop>1,5,12</leftfronttop>
      <rightbackbottom>12,20,16</rightbackbottom>
    </volumeobject>
  </construction>
</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Genotype 71 Soil config/VolumeObjects.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<!-- VolumeObject specification file                                        -->
<!--                                                                        -->
<!-- FORMAT:XML                                                             -->
<!--                                                                        -->
<!-- NO C-style comments                                                    -->
<!--                                                                        -->
<!-- CURRENTLY SUPPORTED CLASSES:                                           -->
<!--                                                                        -->
<!-- BoundingCylinder                                                       -->
<!-- Specifies a cylinder of a given depth, the top disc                    -->
<!-- coplanar with the surface, centred at a given coordinate (with Z=0).   -->
<!-- BoundingCylinders have impenetrable surfaces and do not affect         -->
<!-- the growth rate of root tips growing within them.                      -->
<!--                                                                        -->
<!-- BoundingRectangularPrism                                               -->
<!-- Specifies a right cuboid defined by two points, the left front top     -->
<!-- and right back bottom coordinates. Aligned with the Z-axis             -->
<!-- in the same way as BoundingCylinders.                                  -->
<!-- BoundingRectangularPrisms have impenetrable surfaces and do not affect -->
<!-- the growth rate of root tips growing within them.                      -->
<!--                                                                        -->

<rootmap
        xmlns="https://example.org/ROOTMAP/VolumeObjectsSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/VolumeObjectsSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/VolumeObjects.xsd">
  <construction>
    <owner>VolumeObjectCoordinator</owner>
    <volumeobject>
      <class_name>BoundingCylinder</class_name>
      <origin>5,5,0</origin>
      <depth>60.0</depth>
      <radius>5</radius>
    </volumeobject>
  </construction>
</rootmap>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/config_Genotype85/VolumeObjects.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<!-- VolumeObject specification file                                        -->
<!--                                                                        -->
<!-- FORMAT:XML                                                             -->
<!--                                                                        -->
<!-- NO C-style comments                                                    -->
<!--                                                                        -->
<!-- CURRENTLY SUPPORTED CLASSES:                                           -->
<!--                                                                        -->
<!-- BoundingCylinder                                                       -->
<!-- Specifies a cylinder of a given depth,                                 -->
<!-- the top disc centred at the coordinate <origin>.                       -->
<!-- BoundingCylinders have impenetrable surfaces and do not affect         -->
<!-- the growth rate of root tips growing within them.                      -->
<!--                                                                        -->
<!-- BoundingRectangularPrism                                               -->
<!-- Specifies a right cuboid defined by two points, the left front top     -->
<!-- and right back bottom coordinates. Aligned with the Z-axis             -->
<!-- in the same way as BoundingCylinders.                                  -->
<!-- BoundingRectangularPrisms have impenetrable surfaces and do not affect -->
<!-- the growth rate of root tips growing within them.                      -->
<!--                                                                        -->

<rootmap
        xmlns="https://example.org/ROOTMAP/VolumeObjectsSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/VolumeObjectsSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/VolumeObjects.xsd">
 <construction>
    <owner>VolumeObjectCoordinator</owner>
     <volumeobject>
      <class_name>BoundingCylinder</class_name>
      <root_penetration_probability>
        <top>1.0</top>
        <bottom>0.0</bottom>
        <sides>0.0</sides>
        <probability_calculation_algorithm>Directly Specified</probability_calculation_algorithm>
      </root_penetration_probability>
      <permeability>
        <top>0.0</top>
        <bottom>0.0</bottom>
        <sides>0.0</sides>
      </permeability>
      <origin>8,8,0.1</origin>
      <depth>40.0</depth>
      <radius>7</radius>
    </volumeobject>

   <!--    <volumeobject>
      <class_name>BoundingCylinder</class_name>
      <root_penetration_probability>
        <top>1.0</top>
        <bottom>1.0</bottom>
        <sides>0.0</sides>
        <probability_calculation_algorithm>Directly Specified</probability_calculation_algorithm>
      </root_penetration_probability>
      <permeability>
        <top>0.0</top>
        <bottom>0.0</bottom>
        <sides>0.0</sides>
      </permeability>
      <origin>5,5,70</origin>
      <depth>5.0</depth>
      <radius>4</radius>
    </volumeobject>

        <volumeobject>
      <class_name>BoundingRectangularPrism</class_name>
      <leftfronttop>0,0,0</leftfronttop>
      <rightbackbottom>1,11,50</rightbackbottom>
    </volumeobject>
    <volumeobject>
      <class_name>BoundingRectangularPrism</class_name>
      <leftfronttop>1,0,0</leftfronttop>
      <rightbackbottom>11,1,50</rightbackbottom>
    </volumeobject>
    <volumeobject>
      <class_name>BoundingRectangularPrism</class_name>
      <leftfronttop>10,1,0</leftfronttop>
      <rightbackbottom>11,11,50</rightbackbottom>
    </volumeobject>
    <volumeobject>
      <class_name>BoundingRectangularPrism</class_name>
      <leftfronttop>1,10,0</leftfronttop>
      <rightbackbottom>10,11,50</rightbackbottom>
    </volumeobject>   -->
  </construction>
</rootmap>
