=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Schemata/Windows.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://example.org/ROOTMAP/ViewSchema"
           targetNamespace="https://example.org/ROOTMAP/ViewSchema"
           elementFormDefault="qualified">
    <xsd:include schemaLocation="Common.xsd"/>

    <xsd:element name="rootmap">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="visualisation" type="tns:Visualisation" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Visualisation">
        <xsd:sequence>
            <xsd:element name="owner" type="tns:ViewOwner" minOccurs="1" maxOccurs="1"/>
            <xsd:choice>
                <xsd:element name="table" type="tns:Table" minOccurs="0" maxOccurs="1" />
                <xsd:element name="view" type="tns:View" minOccurs="0" maxOccurs="1" />
                <xsd:element name="view3d" type="tns:View3D" minOccurs="0" maxOccurs="1" />
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Table">
        <xsd:sequence>
            <xsd:element name="process_name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="characteristic_name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="view_direction" type="tns:ViewDirection" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="layer_number" type="xsd:int" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="stratum" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="View">
        <xsd:sequence>
            <xsd:element name="view_direction" type="tns:ViewDirection" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="reference_index" type="tns:Coordinate3D" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="scale" type="xsd:decimal" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="zoom_ratio" type="xsd:decimal" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="repeat" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="wrap" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="boundaries" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="boxes" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="box_colours" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="scoreboards" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="processes" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="characteristics" type="tns:Characteristics" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="View3D">
        <xsd:sequence>
            <xsd:element name="view_position" type="tns:Coordinate3D" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="scale" type="xsd:decimal" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="boundaries" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="boxes" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="box_colours" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="root_radius_multiplier" type="xsd:decimal" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="root_colour_by_branch_order" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="high_contrast_root_colour" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="base_root_red" type="tns:UnitInterval" minOccurs="1" maxOccurs="1" />
            <xsd:element name="base_root_green" type="tns:UnitInterval" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="base_root_blue" type="tns:UnitInterval" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="quality" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="low" />
                        <xsd:enumeration value="medium" />
                        <xsd:enumeration value="high" />
                        <xsd:enumeration value="very high" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="scoreboards" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="processes" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Characteristics">
        <xsd:all>
            <xsd:element name="cyan" type="tns:CharacteristicColourInfo" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="magenta" type="tns:CharacteristicColourInfo" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="yellow" type="tns:CharacteristicColourInfo" minOccurs="1" maxOccurs="1"/>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="CharacteristicColourInfo">
        <xsd:sequence>
            <xsd:element name="colour_min" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:int">
                        <xsd:minInclusive value="0"/>
                        <xsd:maxInclusive value="255"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="colour_max" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:int">
                        <xsd:minInclusive value="0"/>
                        <xsd:maxInclusive value="255"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="characteristic_min" type="xsd:decimal" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="characteristic_max" type="xsd:decimal" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="process_name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="characteristic_name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ROOTMAPSimulationModel/ROOTMAP.Native/Configurations/Genotype 60 Soil config/Windows.xml
<?xml version="1.0" encoding="utf-8"?>

<rootmap
        xmlns="https://example.org/ROOTMAP/ViewSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://example.org/ROOTMAP/ViewSchema https://rootmapstorageaccount.blob.core.windows.net/rootmap-schemata-container/Windows.xsd">
  <visualisation>
    <owner>TableCoordinator</owner>
    <table>
      <process_name>Nitrate</process_name>
      <characteristic_name>Nitrate Concentration</characteristic_name>
      <view_direction>Front</view_direction>
      <layer_number>1</layer_number>
      <stratum>Soil</stratum>
    </table>
  </visualisation>


  <visualisation>
    <owner>ViewCoordinator</owner>
    <view>
      <view_direction>Front</view_direction>
      <reference_index>-5.0,-5.0,-5.0</reference_index>
      <scale>6.5432</scale>
      <zoom_ratio>1.0</zoom_ratio>
      <repeat>false</repeat>
      <wrap>false</wrap>
      <boundaries>true</boundaries>
      <boxes>true</boxes>
      <box_colours>true</box_colours>
      <scoreboards>Soil</scoreboards>
      <processes>Plant 60,Nitrate,Water</processes>
      <characteristics>
        <cyan>
          <colour_min>0</colour_min>
          <colour_max>255</colour_max>
          <characteristic_min>0.0</characteristic_min>
          <characteristic_max>1000.0</characteristic_max>
          <process_name>Phosphorus</process_name>
          <characteristic_name>Total Labile P</characteristic_name>
        </cyan>
        <magenta>
          <colour_min>0</colour_min>
          <colour_max>255</colour_max>
          <characteristic_min>0.0</characteristic_min>
          <characteristic_max>100.0</characteristic_max>
          <process_name>Water</process_name>
          <characteristic_name>Water Content</characteristic_name>
        </magenta>
        <yellow>
          <colour_min>0</colour_min>
          <colour_max>255</colour_max>
          <characteristic_min>0.0</characteristic_min>
          <characteristic_max>1000.0</characteristic_max>
          <process_name>Nitrate</process_name>
          <characteristic_name>Nitrate Concentration</characteristic_name>
        </yellow>
      </characteristics>
    </view>
  </visualisation>


  <visualisation>
    <owner>View3DCoordinator</owner>
    <view3d>
      <!-- view position is the camera's initial offset from the origin -->
      <view_position>0.0,18.0,0.0</view_position>
      <scale>6.5432</scale>
      <boundaries>true</boundaries>
      <boxes>false</boxes>
      <box_colours>false</box_colours>
      <root_radius_multiplier>5.0</root_radius_multiplier>
      <root_colour_by_branch_order>true</root_colour_by_branch_order>
      <high_contrast_root_colour>false</high_contrast_root_colour>
      <base_root_red>0.65</base_root_red>
      <base_root_green>0.49</base_root_green>
      <base_root_blue>0.24</base_root_blue>
      <!-- Supported 3D view quality options are Low, Medium, High and Very High -->
      <quality>low</quality>
      <scoreboards>Soil</scoreboards>
      <processes>Plant 60,Nitrate,VolumeObjectCoordinator</processes>
    </view3d>
  </visualisation>
</rootmap>
